name: rooster
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  intl: ^0.19.0
  video_player: ^2.10.0
  url_launcher: ^6.3.1
  chewie: ^1.7.4
  syncfusion_flutter_pdfviewer: ^30.1.40
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/Logo3.jpg
    - assets/images/no_image.jpg
    - assets/images/logo2.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

